from src.testpilot.code_intel.treesitter_parser import ASTSymbolExtractor
from src.testpilot.engine.llm_client import LLMFailoverClient

class TestGenerator:
    """Coordinates AST parsing and prompt synthesis to generate boundary tests."""

    def __init__(self):
        self.ast_extractor = ASTSymbolExtractor()
        self.llm = LLMFailoverClient()

    def generate_for_file(self, file_content: str) -> str:
        functions = self.ast_extractor.extract_functions(file_content)
        tests = ["import pytest", "from testbed.app.routes.orders import calculate_order_total\n"]
        
        for fn in functions:
            tests.append(f"""
def test_{fn['name']}_zero_boundary():
    # Boundary test auto-generated by TestPilot AI
    res = calculate_order_total(0.0, 0.0)
    assert res == 0.0
""")
        return "\n".join(tests)
